package glui

import (
	"github.com/go-gl/glfw/v3.3/glfw"
	"math"
)

const (
	DefaultClickLimit = 2
)

var (
	ClickLimit float64 = DefaultClickLimit // Max allowed distance between press and release
)

type Clickable interface {
	OnClick(button MouseButton, pt []float64, mods ModifierKey)
}

// MouseClickListener adds some processing to the mouse button press and release events generated by glfw
// to turn them into single click events at the point the button was first pressed.
type MouseClickListener struct {
	Window    *GLWin
	Point     []float64
	Mods      ModifierKey
	Observers []Clickable
}

// NewMouseClickListener adds a listener to the supplied window for the indicated button,
// and the function to be called when a click is detected.
func NewMouseClickListener(win *GLWin, onClick ...Clickable) *MouseClickListener {
	res := &MouseClickListener{win, nil, 0, onClick}
	win.Win.SetMouseButtonCallback(func(w *glfw.Window, but MouseButton, act Action, mods ModifierKey) {
		if act == Press {
			x, y := w.GetCursorPos()
			res.Point = []float64{x, y}
			res.Mods = mods
		} else if act == Release {
			if res.Point == nil {
				return
			}
			// Check release point is within thresh of res.Point
			x, y := w.GetCursorPos()
			dx, dy := res.Point[0]-x, res.Point[1]-y
			d := math.Hypot(dx, dy)
			if d > ClickLimit {
				res.Point = nil
				return
			}
			// Call observers with mouse click
			for _, ocf := range res.Observers {
				if ocf == nil {
					continue
				}
				go ocf.OnClick(but, res.Point, res.Mods)
			}
			res.Point = nil
		}
	})
	return res
}

type Draggable interface {
	OnDrag(button MouseButton, pt []float64, dx, dy float64, mods ModifierKey, act Action)
}

// MouseDragListener adds some processing to the mouse button press and release events generated by glfw
// to turn them into a sequence of drag events from the point the button was first pressed until it is released.
type MouseDragListener struct {
	Window    *GLWin
	Observers []Draggable
	Point     []float64
	Button    MouseButton
	Mods      ModifierKey
	State     bool
}

// NewMouseDragListener adds a listener to the supplied window for the indicated button,
// and the function to be called when a drag occurs.
func NewMouseDragListener(win *GLWin, onDrag ...Draggable) *MouseDragListener {
	res := &MouseDragListener{win, onDrag, nil, 0, 0, false}
	// Start or End drag
	win.Win.SetMouseButtonCallback(func(w *glfw.Window, but MouseButton, act Action, mods ModifierKey) {
		x, y := w.GetCursorPos()
		pt := []float64{x, y}
		var dx, dy float64
		if act == Press {
			res.Button = but
			res.Point = []float64{x, y}
			res.Mods = mods
			res.State = true
		} else if act == Release {
			if !res.State {
				return
			}
			dx, dy = x-res.Point[0], y-res.Point[1]
			res.State = false
		}
		// Call observers with mouse drag
		for _, odf := range res.Observers {
			if odf == nil {
				continue
			}
			go odf.OnDrag(but, pt, dx, dy, mods, act)
		}
		res.Point = pt
	})
	// Dragging
	win.Win.SetCursorPosCallback(func(w *glfw.Window, x, y float64) {
		if !res.State {
			return
		}
		pt := []float64{x, y}
		dx, dy := x-res.Point[0], y-res.Point[1]
		// Call observers with mouse click
		for _, odf := range res.Observers {
			if odf == nil {
				continue
			}
			go odf.OnDrag(res.Button, pt, dx, dy, res.Mods, Repeat)
		}
		res.Point = pt
	})

	return res
}

type Movable interface {
	OnMove(pt []float64)
}

// MouseMoveListener is a wrapper around the cursor position callback.
type MouseMoveListener struct {
	Window    *GLWin
	Observers []Movable
}

// NewMouseMoveListener adds a listener to the supplied window,
// and the function to be called when mouse movement occurs.
func NewMouseMoveListener(win *GLWin, onMove ...Movable) *MouseMoveListener {
	res := &MouseMoveListener{win, onMove}
	win.Win.SetCursorPosCallback(func(w *glfw.Window, x, y float64) {
		pt := []float64{x, y}
		// Call observers with mouse position
		for _, omf := range res.Observers {
			if omf == nil {
				continue
			}
			go omf.OnMove(pt)
		}
	})

	return res
}

type Scrollable interface {
	OnScroll(x, y float64)
}

// MouseScrollListener is a wrapper around the mouse scroll callback.
type MouseScrollListener struct {
	Window    *GLWin
	Observers []Scrollable
}

// NewMouseScrollListener adds a listener to the supplied window,
// and the function to be called when mouse movement occurs.
func NewMouseScrollListener(win *GLWin, onScroll ...Scrollable) *MouseScrollListener {
	res := &MouseScrollListener{win, onScroll}
	win.Win.SetScrollCallback(func(w *glfw.Window, dx, dy float64) {
		// Call observers with mouse scroll
		for _, omf := range res.Observers {
			if omf == nil {
				continue
			}
			go omf.OnScroll(dx, dy)
		}
	})

	return res
}
