package glui

import (
	"github.com/go-gl/glfw/v3.3/glfw"
	"math"
)

const (
	DefaultClickLimit = 2
)

var (
	ClickLimit float64 = DefaultClickLimit // Max allowed distance between press and release
)

type Clickable interface {
	OnClick(mcl *MouseClickListener, button MouseButton, pt []float64, mods ModifierKey)
}

// MouseClickListener adds some processing to the mouse button press and release events generated by glfw
// to turn them into single click events at the point the button was first pressed.
type MouseClickListener struct {
	Window    *GLWin
	Point     []float64
	Mods      ModifierKey
	Observers []Clickable
}

// NewMouseClickListener adds a listener to the supplied window for the indicated button,
// and the function to be called when a click is detected.
func NewMouseClickListener(win *GLWin, onClick ...Clickable) *MouseClickListener {
	res := &MouseClickListener{win, nil, 0, onClick}
	win.Win.SetMouseButtonCallback(func(w *glfw.Window, but MouseButton, act Action, mods ModifierKey) {
		if act == Press {
			x, y := w.GetCursorPos()
			res.Point = []float64{x, y}
			res.Mods = mods
		} else if act == Release {
			if res.Point == nil {
				return
			}
			// Check release point is within thresh of res.Point
			x, y := w.GetCursorPos()
			dx, dy := res.Point[0]-x, res.Point[1]-y
			d := math.Hypot(dx, dy)
			if d > ClickLimit {
				res.Point = nil
				return
			}
			// Call observers with mouse click
			res.Click(but, res.Point, res.Mods)
			res.Point = nil
		}
	})
	return res
}

func (mcl *MouseClickListener) Click(but MouseButton, pt []float64, mods ModifierKey) {
	for _, ocf := range mcl.Observers {
		if ocf == nil {
			continue
		}
		go ocf.OnClick(mcl, but, pt, mods)
	}
}

type Draggable interface {
	OnDrag(mdl *MouseDragListener, button MouseButton, pt []float64, dx, dy float64, act Action, mods ModifierKey)
}

// MouseDragListener adds some processing to the mouse button press and release events generated by glfw
// to turn them into a sequence of drag events from the point the button was first pressed until it is released.
type MouseDragListener struct {
	Window    *GLWin
	Observers []Draggable
	Point     []float64
	Button    MouseButton
	Mods      ModifierKey
	State     bool
}

// NewMouseDragListener adds a listener to the supplied window for the indicated button,
// and the function to be called when a drag occurs.
func NewMouseDragListener(win *GLWin, onDrag ...Draggable) *MouseDragListener {
	res := &MouseDragListener{win, onDrag, nil, 0, 0, false}
	// Start or End drag
	win.Win.SetMouseButtonCallback(func(w *glfw.Window, but MouseButton, act Action, mods ModifierKey) {
		x, y := w.GetCursorPos()
		pt := []float64{x, y}
		var dx, dy float64
		if act == Press {
			res.Button = but
			res.Point = []float64{x, y}
			res.Mods = mods
			res.State = true
		} else if act == Release {
			if !res.State {
				return
			}
			dx, dy = x-res.Point[0], y-res.Point[1]
			res.State = false
		}
		res.Drag(but, pt, dx, dy, act, mods)
		res.Point = pt
	})
	// Dragging
	win.Win.SetCursorPosCallback(func(w *glfw.Window, x, y float64) {
		if !res.State {
			return
		}
		pt := []float64{x, y}
		dx, dy := x-res.Point[0], y-res.Point[1]
		res.Drag(res.Button, pt, dx, dy, Repeat, res.Mods)
		res.Point = pt
	})

	return res
}

func (mdl *MouseDragListener) Drag(but MouseButton, pt []float64, dx, dy float64, act Action, mods ModifierKey) {
	for _, odf := range mdl.Observers {
		if odf == nil {
			continue
		}
		go odf.OnDrag(mdl, but, pt, dx, dy, act, mods)
	}
}

type Movable interface {
	OnMove(mml *MouseMoveListener, pt []float64)
}

// MouseMoveListener is a wrapper around the cursor position callback.
type MouseMoveListener struct {
	Window    *GLWin
	Observers []Movable
}

// NewMouseMoveListener adds a listener to the supplied window,
// and the function to be called when mouse movement occurs.
func NewMouseMoveListener(win *GLWin, onMove ...Movable) *MouseMoveListener {
	res := &MouseMoveListener{win, onMove}
	win.Win.SetCursorPosCallback(func(w *glfw.Window, x, y float64) {
		res.Move([]float64{x, y})
	})

	return res
}

func (mml *MouseMoveListener) Move(pt []float64) {
	for _, omf := range mml.Observers {
		if omf == nil {
			continue
		}
		go omf.OnMove(mml, pt)
	}
}

type Scrollable interface {
	OnScroll(msl *MouseScrollListener, x, y float64)
}

// MouseScrollListener is a wrapper around the mouse scroll callback.
type MouseScrollListener struct {
	Window    *GLWin
	Observers []Scrollable
}

// NewMouseScrollListener adds a listener to the supplied window,
// and the function to be called when mouse movement occurs.
func NewMouseScrollListener(win *GLWin, onScroll ...Scrollable) *MouseScrollListener {
	res := &MouseScrollListener{win, onScroll}
	win.Win.SetScrollCallback(func(w *glfw.Window, dx, dy float64) {
		res.Scroll(dx, dy)
	})

	return res
}

func (msl *MouseScrollListener) Scroll(dx, dy float64) {
	for _, omf := range msl.Observers {
		if omf == nil {
			continue
		}
		go omf.OnScroll(msl, dx, dy)
	}
}
